version: '3.1'

services:
  university-crew-db:
    container_name: university-crew-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - university-crew-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: university_db
      MYSQL_USER: test
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3300:3306

volumes:
  university-crew-db-volume: