spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3300/university_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: test
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: false
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  main:
    banner-mode: off

reader:
  files:
    helpfile: src/main/resources/static/files/UC-help.txt
logging:
  pattern:
    console:
